# Generated by Django 4.1.7 on 2023-03-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('transactionid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.PositiveSmallIntegerField(choices=[(10, 'Зачисление Денег'), (20, 'Списание Вывод'), (30, 'Инвестиционный пакет'), (50, 'Зачисление с Инвест Пакета'), (60, 'Зачисления Реф')])),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('I', 'Зачислено'), ('O', 'Выведено'), ('W', 'Ожидание')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
