# Generated by Django 4.1.7 on 2023-03-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('period', models.PositiveSmallIntegerField()),
                ('percent', models.PositiveSmallIntegerField()),
                ('min_amount', models.PositiveSmallIntegerField()),
                ('max_amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackagesActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.FloatField()),
                ('start_date_package', models.DateTimeField(auto_now_add=True)),
                ('end_amount', models.FloatField()),
                ('end_date_package', models.DateTimeField()),
                ('package', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
